name: MyWorldsLite
main: com.bergerkiller.bukkit.mw.MyWorldsLite
version: 0.1

authors: [ bergerkiller, BangL ]
depend: [ BKCommonLib ]
loadbefore:
- CasinoSlots
- CopyBooks
- ChunkFixer
- Citizens
- ClayGen
- DeathCube
- DragonTravel
- Dynmap
- ecoCreature
- EndReset
- Essentials
- FreezeTime
- HawkEye
- HiddenCommandSigns
- LotManager
- LWC
- MineBooks
- MobArena
- MobRider
- MonsterBox
- PermissionsEx
- PlayerStatusSigns
- PortalBlocks
- ShowCaseStandalone
- SignEdit
- SignLink
- SimpleCommandSigns
- SimpleClans
- SimpleSpleef
- SpongeReloaded
- SwornJail
- Timer
- War
- WorldBorder
- WorldEdit
- WorldGuard

commands:
    world:
        description: Commands to manage your worlds
        aliases: [myworlds, mw, worlds]
        usage: |
            Use /help world [subcommand] for more information
            /world info - Show world information
            /world list - List all worlds
            /world load - Load an existing world
            /world unload - Unload a loaded world
            /world save - Save a loaded world
            /world create - Create a new world
            /world listgenerators - List world generators
            /world setspawn - Set the spawn point of a world
            /world spawn - Teleport to world spawn
            /world gamemode - Set the game mode of a world
            /world difficulty - Set the difficulty of a world
            /world saving - Toggle world saving on/off
            /world spawnloaded - Toggle spawn loaded on/off
            /world delete - Delete a world permanently
            /world copy - Copy a world to a new name
            /world repair - Repair a world
    world info:
        description: Shows detailed information of a world
        aliases: [world i]
        usage: |
            /world info
            /world info [worldname]
    world list:
        description: Lists all the worlds of the server
        usage: /world list
    world load:
        description: Loads a world
        usage: /world load [worldname]
    world unload:
        description: Unloads a world
        usage: /world unload [worldname]
    world save:
        description: Save a world
        usage: |
            /world save - Save the world you are in
            /world save [worldname] - Save worldname
            /world save [all/*] - Save all worlds
    world create:
        description: Create a new world
        usage: |
            /world create [world]_[env]:[gen]:[genarg] [seed]
            /world create NormalWorld1 SomeSeed
            /world create world2_nether MySeed
            /world create world3:Plots:64 -45245253
            /world create someworld_the_end
    world listgenerators:
        description: List all world generators
        aliases: [world generators, world gen, world listgen]
        usage: /world listgenerators
    world setspawn:
        description: Sets the spawn point of the world to your position
        usage: |
            /world setspawn - set spawn of current world
            /world setspawn [worldname] - set spawn of a world
    world spawn:
        description: Teleports you or players specified to the world spawn
        usage: |
            /world spawn - Teleport to current world spawn
            /world spawn [world] - Teleport to world spawn
            /world spawn [world] [playernames] - Teleport players
    world gamemode:
        description: Sets the game mode of a world
        usage: |
            /world gamemode [mode]
            /world gamemode [mode] [world]
            /world gamemode creative
            /world gamemode survival world3
    world difficulty:
        description: Sets the difficulty of a world
        usage: |
            /world difficulty [mode]
            /world difficulty [mode] [world]
            /world difficulty hard
            /world difficulty normal world3
    world saving:
        description: Turns world saving on or off
        usage: |
            /world saving [enable/disable]
            /world saving [enable/disable] [world]
            /world saving off
            /world saving enable world2
    world spawnloaded:
        description: Toggles if the world spawn is kept loaded
        usage: |
            /world spawnloaded
            /world spawnloaded [world]
    world delete:
        description: Deletes an unloaded world
        usage: /world delete [world]
    world copy:
        description: Copies a world
        usage: /world copy [world_from] [world_to]
    world repair:
        description: Repairs an unloaded world
        usage: /world repair [world]
