name: My Worlds
main: com.bergerkiller.bukkit.mw.MyWorlds
version: 1.28
author: bergerkiller
commands:
    world:
        description: Cross-world commands to manage your worlds
        aliases: [myworlds, mw, worlds]
        usage: |
            /world ? for usage
    tpp:
        description: Cross-world teleportation commands
        usage: /tpp [Portalname/Worldname] - Teleport to a Portal or World
permissions:
    myworlds.world.list:
        description: Sets if the player can list all worlds on the server
        default: op
    myworlds.world.info:
        description: Sets if the player can see world information, such as the seed and size
        default: op
    myworlds.world.config:
        description: Sets if the player can manually load and save the world configuration
        default: op
    myworlds.world.portals:
        description: Sets if the player can list all portals on the server
        default: op
    myworlds.world.listgenerators:
        description: Sets if the player can list all chunk generators on the server
        default: op
    myworlds.world.setportal:
        description: Sets if the player can change the default portal destination on the world
        default: op
    myworlds.world.load:
        description: Sets if the player can load unloaded worlds (not create)
        default: op
    myworlds.world.unload:
        description: Sets if the player can unload loaded worlds (not create)
        default: op
    myworlds.world.create:
        description: Sets if the player can create worlds (not replace)
        default: op
    myworlds.world.spawn:
        description: Sets if the player can teleport to world spawn points
        default: op
    myworlds.world.evacuate:
        description: Sets if the player can clear a world from its players
        default: op
    myworlds.world.repair:
        description: Sets if the player can repair damaged worlds (only if broken)
        default: op
    myworlds.world.save:
        description: Sets if the player can save worlds
        default: op
    myworlds.world.setsaving:
        description: Sets if the player can toggle world auto-saving on or off
        default: op
    myworlds.world.delete:
        description: Sets if the player can permanently delete worlds
        default: false
    myworlds.world.copy:
        description: Sets if the player can clone worlds
        default: false
    myworlds.world.difficulty:
        description: Sets if the player can change the difficulty setting of worlds
        default: op
    myworlds.world.togglepvp:
        description: Sets if the player can change the PvP setting of worlds
        default: op
    myworlds.world.op:
        description: Sets if the player can add operators to a world
        default: op
    myworlds.world.deop:
        description: Sets if the player can remove operator from a world
        default: op
    myworlds.world.togglespawnloaded:
        description: Sets if the player can toggle spawn chunk loading on or off
        default: op
    myworlds.world.allowspawn:
        description: Sets if the player can start mobs spawning
        default: op
    myworlds.world.denyspawn:
        description: Sets if the player can stop mobs from spawning
        default: op
    myworlds.world.weather:
        description: Sets if the player can change the weather on worlds
        default: op
    myworlds.world.time:
        description: Sets if the player can change the time on worlds
        default: op
    myworlds.world.gamemode:
        description: Sets if the player can change the gamemode of a world
        default: op
    myworlds.world.setspawn:
        description: Sets if the player can change the spawn point of a world
        default: op
    myworlds.world.teleport.*:
        description: Sets the worlds a player can teleport to using /tpp and /world spawn
        default: op
    myworlds.world.enter.*:
        description: Sets if the player can enter a certain world through portals
        default: op;
    myworlds.world.build.*:
        description: Sets if the player can build in a certain world
        default: op
    myworlds.world.use.*:
        description: Sets if the player can interact with blocks in a certain world
        default: op
    myworlds.portal.create:
        description: Sets if the player can create teleport signs
        default: op
    myworlds.portal.override:
        description: Sets if the player can replace existing portals
        default: op
    myworlds.portal.use:
        description: Sets if the player can use portals
        default: true
    myworlds.portal.teleport.*:
        description: Sets the portals a player can teleport to using /tpp
        default: op
    myworlds.portal.enter.*:
        description: Sets if the player can enter a certain portal
        default: op
    myworlds.tpp:
        description: Sets if the player can teleport to worlds or portals
        default: op